---
- name: Update repository Ubuntu
  hosts: myhost
  become: true

  tasks: 
  - name: Run the equivalent of "apt-get update" as a separate step
    apt:
      update_cache: yes
  
  - name: install mysql server
    yum:
      name: mysql-server
      state: latest
  - name: enable service mysql (autostart on boot)
    service:
      name: mysql
      enabled: yes
  - name: start service mysql
    service:
      name: mysql
      state: started 